name: firebase_storage_web
description: The web implementation of firebase_storage
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
version: 3.3.16

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  _flutterfire_internals: ^1.0.9
  async: ^2.5.0
  firebase_core: ^2.3.0
  firebase_core_web: ^2.0.1
  firebase_storage_platform_interface: ^4.1.24
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_core_platform_interface: ^4.5.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseStorageWeb
        fileName: firebase_storage_web.dart
