name: firebase_storage
description: Flutter plugin for Firebase Cloud Storage, a powerful, simple, and
  cost-effective object storage service for Android and iOS.
homepage: https://firebase.flutter.dev/docs/storage/overview
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage
version: 11.0.6

false_secrets:
  - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^2.3.0
  firebase_core_platform_interface: ^4.5.2
  firebase_storage_platform_interface: ^4.1.24
  firebase_storage_web: ^3.3.16
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.storage
        pluginClass: FlutterFirebaseStoragePlugin
      ios:
        pluginClass: FLTFirebaseStoragePlugin
      macos:
        pluginClass: FLTFirebaseStoragePlugin
      web:
        default_package: firebase_storage_web
