name: example
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit:
    path: ../

flutter:
  uses-material-design: true
